development:
  adapter: postgresql
  encoding: unicode
  database: gt_auth_development
  host: localhost
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gt_auth_test
  host: localhost
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gt_auth_production
  host: localhost
  pool: 5
  username:
  password:
